apiVersion: opencontext.com/v1alpha1
kind: CodeComponent
metadata:
  name: spinnaker-pipeline-trigger
  description: Trigger Spinnaker pipelines via GitHub Actions
  title: Spinnaker Pipeline Trigger
  links:
    - title: Spinnaker Website
      url: https://spinnaker.io
    - title: Spinnaker Docs
      url: https://spinnaker.io/docs/
    - title: Spinnaker Slack
      url: https://spinnakerteam.slack.com

  annotations:
    github.com/project-slug: 'alchen99/spinnaker-pipeline-trigger'
spec:
  type: other
  otherType: github-actions
  lifecycle: production
  owner: [user:alice]
  uri: https://localhost:7001
  priority: 3
  sla: 24x5
  isInternal: true
  isSaas: false
  requiresLicense: false
  isPageable: false
