name: "Test"
on:
  pull_request:
    branches:
      - main

jobs:
  test: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - run: |
          jq -r '.' <<<'${{ steps.files.outputs.removed }}'
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - run: |
          yarn
      - run: |
          yarn all
