name: "Test"
on:
  pull_request:
    branches:
      - main

jobs:
  test: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - run: |
          yarn
      - run: |
          set -x
          export GIT_ADD_MODIFIED=$(jq --arg GHPATH "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/contents/" -r 'map({ (.): ($GHPATH + .)}) | add' <<<'${{ steps.files.outputs.added_modified }}')
          set +x
          env | grep GIT 
          yarn all
